### PR TITLE
Repo defaults

### LINKED ISSUE #1: Set up repo security and defaults
## Description
Set branch security and issue templets for the repo.

NOTE: Repo admin access is required for this. 

## Acceptance Criteria
- [x] The `Main` branch has merge security so that branch/PR cannot be merged without 2 review.
- [x] There is a template issue for tasks, bugs and features.
- [x] Custom labels created to use in the repo

### PR DESCRIPTION
**Pull request by CalebMcOlin**
## Description
closes #1 

**Templates:**
- This adds new issue templates to the repo for quick, easy, and readable issue creation. This will also ensure all developers are on the same page when dealing with issues created by someone else.
- There is not a basic PR template

**Labels:**
- The Labels have already been created and added to the repo. If you see/want changes to these let me know.

**Branch Security:**
- This has to be done by the repo owner (Brenden). I'll be going over this with him in our client meeting tomorrow.

## To Test
1. Click "Issues" on the GitHub repo 
2. Click "New Issue"
3. Open the new files `bug-report.md`, `feature-request.md`, and `standard-issue.md` 
4. Copy and paste contents of each file _**starting at line 10**_. (Do this one file at a time)
5. Check for spelling/grammar errors
6. Ensure the template looks/reads well

### CODE REVIEW

**Review by nataliagourova — APPROVED** [review]
Good stuff, thank you for doing this, Caleb!

**Comment by CalebMcOlin** [comment]
Moved to Draft because the 'Branch Security' is reliant on the client meeting tomorrow.

**Review by dagmawidemissie17 — APPROVED** [review]
Nice work Caleb! This is a neat template.

**Comment by CalebMcOlin** [comment]
Branch security was completed by Brenden 🎉

**Pull request merged**
