### PR TITLE
Setup main menu

### LINKED ISSUE #7: Trim/Clean up code
### Description 
There appears to be a lot of unnecessary comments on these some of the files.
We need to trim/clean up our code at some point.
Also any template starting code can be removed so it doesn't clutter the codebase

### Context / Additional Information
image
See the comments on closed PR #2 for more information

### Acceptance Criteria
- [ ] Unnecessary comments are removed
- [ ] Unneeded starting template code is removed
- [ ] The codebase is cleaned and orginized

### PR DESCRIPTION
**Pull request by CalebMcOlin**
## Description
closes #7 
- This creates the base structure for the `Home View` and the folder structure for components.
- The starting `App.js` was wiped clean and given a basic starting layout
- Multiple files were cleaned up
- Folder/file structure: `components/screens/{ComponentNameFolder}/{ComponentNameFile(.js, .css, .png)}/`

**NOTE:**
Styling was not a priority with this work as the UI library has not yet been implemented.

## To Test
1. Switch to the `setup-main-menu` branch
2. Pull the changes
3. Start the metro
4. Start the app
5. Verify the home page looks correct

6. Verify the buttons work

### CODE REVIEW

**Review by zmagar — APPROVED** [review]
I was able to load the app, main screen:
Screenshot 2021-10-14 103153
Good work! 
I'm not sure about using SafeAreaView which is applicable to IOS only, though. It shouldn't affect Android but I guess we need to discuss some coding guidelines.

**Review by zmagar — CHANGES_REQUESTED** [review]
HomeScreen looks good except for the different background color:
Screenshot 2021-10-14 103153

**Comment by CalebMcOlin** [comment]
Thanks for the feedback. I've fixed the typo and renamed the HomeScreen functional component.

Also, the dark grey background is because my test device is on "Dark Mode". I've tested switching it from Dark Mode to Light Mode and it shows correctly in both settings. I'll keep it on Light Mode from now until we decide to test out the Dark Mode specifically.

**Review by zmagar — APPROVED** [review]
LGTM!

**Review by dagmawidemissie17 — APPROVED** [review]
Nice work!

**Pull request merged**
